### PR TITLE
feat: reload and reconnect the app process after updating files

### PR DESCRIPTION
**Pull request by zimeg**
### Type of change

- [ ] New sample
- [x] New feature
- [ ] Bug fix
- [ ] Documentation

### Summary

This PR automatically reloads the process and reconnects the Socket Mode connection after a file is changed. All in hopes of improving the development experience.

### Reviewers

```sh
$ slack create asdf -t slack-samples/bolt-python-custom-function-template -b zimeg/feat-start-reload
$ cd asdf
$ slack run           # Run the app in some separate window
$ vim app.py          # Make a change to the app and watch a reload
$ vim manifest.json   # Update the manifest and notice the app is reinstalled
$ slack delete
$ cd .. && rm -rf asdf
```

### Notes

- https://github.com/breuleux/jurigged

### Requirements

- [x] I’ve checked my submission against the Samples Checklist to ensure it complies with all standards
- [x] I have ensured the changes I am contributing align with existing patterns and have tested and linted my code
- [x] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct)

### CODE REVIEW

**Comment by zimeg** [comment]
🗒️ Marking this as draft to gather feedback before making more changes!

**Comment by zimeg** [comment]
Finding that [reloadium](https://github.com/reloadware/reloadium) might not be compatible on some versions of Python and OS/arch - I think 3.9 and darwin/x86-64 was causing problems cc: @srtaalej 🤔 So this was updated.

The [jurigged](https://github.com/breuleux/jurigged) tool seems like a powerful alternative and I didn't find problems with decorated handlers which might be one of [the noted concerns](https://github.com/breuleux/jurigged?tab=readme-ov-file#troubleshooting) 😳

> There may be issues updating some functions when they are decorated or stashed in some data structure that Jurigged does not understand. Jurigged does have to find them to update them, unfortunately.

The `DEBUG` logging is also noisy but `INFO` feels quiet - I didn't realize updates were happening at first! I think the hot reloading means Socket Mode doesn't need to reconnect when updates happen. Much different than `nodemon`!

I'm impressed after a bit of testing! 😄

**Review by WilliamBergamin — CHANGES_REQUESTED** [review]
This is awesome work 🏆  I love the idea of hot reloading python 💯 

But I don't think we should advertise `jurigged` in our sample project, this may lead developers to expect compatibility between our projects and `jurigged`. We would also need to ensure that the hot reloading works for different versions of the project, automated testing for this may be tricky 

It might be easier to document this in the `README.md` where we can explain how to set up this functionality locally

**Comment by zimeg** [comment]
@WilliamBergamin thanks for checking this out! I agree that compatibility across systems can be concerning and I don't have a strong answer to this... Being a bit opinionated about tooling seems alright to me if that concern is covered with tests though, but that does seem like a tricky matrix to cover.

> We could also try to add this feature to the `python-slack-hooks` project 🤔

I'm a fan of this direction! IMO adding a dependency like this behind the `start` hook would be most ideal and save a lot of development time over other implementations. The message protocols would even allow us to `DEBUG` to the CLI `--verbose` logs 👀

Planning to discuss more of this soon, but I think hooks are the better way 🙌

**Comment by zimeg** [comment]
@WilliamBergamin all solid checks and review and discussion. It seems like documenting this as a possible behavior is the way to go for now, so going to close this PR with plans to follow up with documentation in some expected place!

**Pull request closed without merging**
